project:"Flower Garden Banks Data Dashboard"
output-dir: _output
toc: true
number-sections: true
bibliography: references.bib  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true 
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Locations"
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Information"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
