name: "FGBNMS_DBv3"
toc: false
number-sections: false
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true 
website:
  sidebar:
    style: "docked"
    search: false
    contents:
      - section: "Locations"
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Information"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
