project:
  type: website
  output-dir: docs
  resources:
    - "/.nojekyll"

website:
  title: "FGBNMS Data Dashboard"
  sidebar:
    style: "docked"
    search: false
    contents:
      - section: "Bank Locations"
        contents:
          - EFGB.qmd
          - WFGB.qmd
          - STET.qmd
      - section: "Other information"
        contents:
          - discharge.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: false

execute:
  echo: false
  warning: false
