---
title: "East Flower Garden Banks"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# install.packages("tidyverse")
# install.packages("plotly")
# put your libary loading here:
library(tidyverse)
library(plotly)
```
## Satellite data extracted at East Flower Gardens

### Chlorophyll-a
::: {.panel-tabset}
### Mean
```{r}
#| column: screen-inset-right
ts <- read_csv("data/FGBdbv2_chlor_a_TS_MODA_daily_EFG.csv", col_types=cols())  # Pull CHL ts from .csv (need to fix source here to server, NOT Github!)

# convert dates
dates <- ts$Time %>%
    as.numeric() %>%
    as.POSIXct(origin = "1970-01-01", tz = "GMT")

# use plotly
plt <- plot_ly(ts, type = 'scatter', mode = 'lines')%>%
  add_trace(x = dates, y = ts$mean)%>%
  layout(showlegend = F)
plt <- plt %>% add_trace(x = dates, y = ts$climatology, name = 'climatology', mode = 'lines')
plt

# How to suppress warnings?
# How can we fill gaps between points?
# Can user turn climatology in first plot on and off? Or make transparent?

```
### Anomaly
```{r}
# plot
plot_ly(ts, type = 'scatter', mode = 'lines')%>%
  add_trace(x = dates, y = ts$anomaly)%>%
  layout(showlegend = F)



```
:::



